version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "3000:3000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318/v1/traces
      - OTEL_SERVICE_NAME=auth-service
    depends_on:
      - otel-collector

  products-service:
    build: ./products-service
    ports:
      - "3001:3001"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318/v1/traces
      - OTEL_SERVICE_NAME=products-service
    depends_on:
      - otel-collector

  cart-service:
    build: ./cart-service
    ports:
      - "3002:3002"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318/v1/traces
      - OTEL_SERVICE_NAME=cart-service
    depends_on:
      - otel-collector

  orders-service:
    build: ./orders-service
    ports:
      - "3003:3003"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318/v1/traces
      - OTEL_SERVICE_NAME=orders-service
    depends_on:
      - otel-collector

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318/v1/traces
      - OTEL_SERVICE_NAME=api-gateway
    depends_on:
      - otel-collector

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api-gateway


  jaeger:
    image: jaegertracing/all-in-one:1.55
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"
      - "14250:14250"
      - "9411:9411" 
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.128.0
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    ports:
      - "4318:4318"
      - "4317:4317"
    depends_on:
      - jaeger
