receivers:
  otlp:
    protocols:
      http:

exporters:
  zipkin:
    endpoint: http://jaeger:9411/api/v2/spans

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin]

