receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  zipkin:
    endpoint: http://jaeger:9411/api/v2/spans  # ✅ correct path

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin]

