mode: deployment

fullnameOverride: otel-collector

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.128.0
  pullPolicy: IfNotPresent

config:
  extensions:
    health_check:
      endpoint: "0.0.0.0:13133"

  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

  processors:
    batch: {}

  exporters:
    otlp/jaeger:
      endpoint: jaeger-collector.jaeger.svc.cluster.local:4317
      tls:
        insecure: true
    debug:
      verbosity: detailed

  service:
    extensions: [health_check]
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp/jaeger, debug]
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [debug]
      logs:
        receivers: [otlp]
        processors: [batch]
        exporters: [debug]

service:
  type: ClusterIP

ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317

  otlp-http:
    enabled: true
    containerPort: 4318
    servicePort: 4318

  health:
    enabled: true
    containerPort: 13133
    servicePort: 13133

