apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: jaeger

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: jaeger-deployment
    namespace: jaeger
    labels:
      app: jaeger
      jaeger-infra: jaeger-deployment
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: jaeger
        jaeger-infra: jaeger-pod
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: jaeger
          jaeger-infra: jaeger-pod
      spec:
        containers:
        - name: jaeger
          image: jaegertracing/all-in-one
          env:
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: ":9411"
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 16686
              protocol: TCP
            - containerPort: 9411
              protocol: TCP
            - containerPort: 14267
              protocol: TCP
            - containerPort: 14268
              protocol: TCP
            - containerPort: 14250
              protocol: TCP
            - containerPort: 4317
              protocol: TCP
            - containerPort: 4318
              protocol: TCP
          readinessProbe:
            httpGet:
              path: "/"
              port: 16686
            initialDelaySeconds: 5

- apiVersion: v1
  kind: Service
  metadata:
    name: jaeger-query
    namespace: jaeger
    labels:
      app: jaeger
      jaeger-infra: jaeger-service
  spec:
    ports:
      - name: query-http
        port: 80
        protocol: TCP
        targetPort: 16686
    selector:
      jaeger-infra: jaeger-pod
    type: LoadBalancer

- apiVersion: v1
  kind: Service
  metadata:
    name: jaeger-collector
    namespace: jaeger
    labels:
      app: jaeger
      jaeger-infra: collector-service
  spec:
    type: ClusterIP
    selector:
      jaeger-infra: jaeger-pod
    ports:
      - name: jaeger-collector-tchannel
        port: 14267
        targetPort: 14267
        protocol: TCP
      - name: jaeger-collector-http
        port: 14268
        targetPort: 14268
        protocol: TCP
      - name: jaeger-collector-zipkin
        port: 9411
        targetPort: 9411
        protocol: TCP
      - name: grpc-jaeger
        port: 14250
        targetPort: 14250
        protocol: TCP
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP

- apiVersion: v1
  kind: Service
  metadata:
    name: jaeger-agent
    namespace: jaeger
    labels:
      app: jaeger
      jaeger-infra: agent-service
  spec:
    clusterIP: None
    selector:
      jaeger-infra: jaeger-pod
    ports:
      - name: agent-zipkin-thrift
        port: 5775
        protocol: UDP
        targetPort: 5775
      - name: agent-compact
        port: 6831
        protocol: UDP
        targetPort: 6831
      - name: agent-binary
        port: 6832
        protocol: UDP
        targetPort: 6832

- apiVersion: v1
  kind: Service
  metadata:
    name: zipkin
    namespace: jaeger
    labels:
      app: jaeger
      jaeger-infra: zipkin-service
  spec:
    clusterIP: None
    selector:
      jaeger-infra: jaeger-pod
    ports:
      - name: jaeger-collector-zipkin
        port: 9411
        targetPort: 9411
        protocol: TCP

