# Rollout for auth-service
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: sreedocker123/cafemicroserviceauth:latest
          ports:
            - containerPort: 3000
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4318/v1/traces"
            - name: OTEL_SERVICE_NAME
              value: "auth-service"
  strategy:
    canary:
      stableService: auth-service-stable
      canaryService: auth-service-preview
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 30s }
        - analysis:
            templates:
              - templateName: rollout-analysis
            args:
              - name: service-name
                value: auth-service-preview

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service-stable
spec:
  selector:
    app: auth-service
    rollouts-pod-template-hash: placeholder-stable
  ports:
    - port: 3000
      targetPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service-preview
spec:
  selector:
    app: auth-service
    rollouts-pod-template-hash: placeholder-preview
  ports:
    - port: 3000
      targetPort: 3000

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: auth-service
  annotations:
    argoproj.io/managed-by-rollouts: "true"
spec:
  hosts:
    - auth-service.default.svc.cluster.local
  gateways:
    - mesh
  http:
    - route:
        - destination:
            host: auth-service-stable
            port:
              number: 3000
          weight: 100
        - destination:
            host: auth-service-preview
            port:
              number: 3000
          weight: 0

---

# Rollout for products-service
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: products-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-service
  template:
    metadata:
      labels:
        app: products-service
    spec:
      containers:
        - name: products-service
          image: sreedocker123/cafemicroserviceproducts:latest
          ports:
            - containerPort: 3001
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4318/v1/traces"
            - name: OTEL_SERVICE_NAME
              value: "products-service"
  strategy:
    canary:
      stableService: products-service-stable
      canaryService: products-service-preview
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 30s }
        - analysis:
            templates:
              - templateName: rollout-analysis
            args:
              - name: service-name
                value: products-service-preview

---

apiVersion: v1
kind: Service
metadata:
  name: products-service-stable
spec:
  selector:
    app: products-service
    rollouts-pod-template-hash: placeholder-stable
  ports:
    - port: 3001
      targetPort: 3001

---

apiVersion: v1
kind: Service
metadata:
  name: products-service-preview
spec:
  selector:
    app: products-service
    rollouts-pod-template-hash: placeholder-preview
  ports:
    - port: 3001
      targetPort: 3001

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: products-service
  annotations:
    argoproj.io/managed-by-rollouts: "true"
spec:
  hosts:
    - products-service.default.svc.cluster.local
  gateways:
    - mesh
  http:
    - route:
        - destination:
            host: products-service-stable
            port:
              number: 3001
          weight: 100
        - destination:
            host: products-service-preview
            port:
              number: 3001
          weight: 0

---

# Rollout for cart-service
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: sreedocker123/cafemicroservicecart:latest
          ports:
            - containerPort: 3002
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4318/v1/traces"
            - name: OTEL_SERVICE_NAME
              value: "cart-service"
  strategy:
    canary:
      stableService: cart-service-stable
      canaryService: cart-service-preview
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 30s }
        - analysis:
            templates:
              - templateName: rollout-analysis
            args:
              - name: service-name
                value: cart-service-preview

---

apiVersion: v1
kind: Service
metadata:
  name: cart-service-stable
spec:
  selector:
    app: cart-service
    rollouts-pod-template-hash: placeholder-stable
  ports:
    - port: 3002
      targetPort: 3002

---

apiVersion: v1
kind: Service
metadata:
  name: cart-service-preview
spec:
  selector:
    app: cart-service
    rollouts-pod-template-hash: placeholder-preview
  ports:
    - port: 3002
      targetPort: 3002

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: cart-service
  annotations:
    argoproj.io/managed-by-rollouts: "true"
spec:
  hosts:
    - cart-service.default.svc.cluster.local
  gateways:
    - mesh
  http:
    - route:
        - destination:
            host: cart-service-stable
            port:
              number: 3002
          weight: 100
        - destination:
            host: cart-service-preview
            port:
              number: 3002
          weight: 0

---

# Rollout for orders-service
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: orders-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          image: sreedocker123/cafemicroserviceorders:latest
          ports:
            - containerPort: 3003
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4318/v1/traces"
            - name: OTEL_SERVICE_NAME
              value: "orders-service"
  strategy:
    canary:
      stableService: orders-service-stable
      canaryService: orders-service-preview
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 30s }
        - analysis:
            templates:
              - templateName: rollout-analysis
            args:
              - name: service-name
                value: orders-service-preview

---

apiVersion: v1
kind: Service
metadata:
  name: orders-service-stable
spec:
  selector:
    app: orders-service
    rollouts-pod-template-hash: placeholder-stable
  ports:
    - port: 3003
      targetPort: 3003

---

apiVersion: v1
kind: Service
metadata:
  name: orders-service-preview
spec:
  selector:
    app: orders-service
    rollouts-pod-template-hash: placeholder-preview
  ports:
    - port: 3003
      targetPort: 3003

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: orders-service
  annotations:
    argoproj.io/managed-by-rollouts: "true"
spec:
  hosts:
    - orders-service.default.svc.cluster.local
  gateways:
    - mesh
  http:
    - route:
        - destination:
            host: orders-service-stable
            port:
              number: 3003
          weight: 100
        - destination:
            host: orders-service-preview
            port:
              number: 3003
          weight: 0

---

# Rollout for api-gateway
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: sreedocker123/cafemicroserviceapigateway:latest
          ports:
            - containerPort: 8000
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4318/v1/traces"
            - name: OTEL_SERVICE_NAME
              value: "api-gateway"
  strategy:
    canary:
      stableService: api-gateway-stable
      canaryService: api-gateway-preview
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 30s }
        - analysis:
            templates:
              - templateName: rollout-analysis
            args:
              - name: service-name
                value: api-gateway-preview

---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway-stable
spec:
  selector:
    app: api-gateway
    rollouts-pod-template-hash: placeholder-stable
  ports:
    - port: 8000
      targetPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway-preview
spec:
  selector:
    app: api-gateway
    rollouts-pod-template-hash: placeholder-preview
  ports:
    - port: 8000
      targetPort: 8000

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: api-gateway
  annotations:
    argoproj.io/managed-by-rollouts: "true"
spec:
  hosts:
    - api-gateway.default.svc.cluster.local
  gateways:
    - mesh
  http:
    - route:
        - destination:
            host: api-gateway-stable
            port:
              number: 8000
          weight: 100
        - destination:
            host: api-gateway-preview
            port:
              number: 8000
          weight: 0

---

# Rollout for frontend
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: sreedocker123/cafemicroservicefrontend:canary2
          ports:
            - containerPort: 80
  strategy:
    canary:
      stableService: frontend-stable
      canaryService: frontend-preview
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 30s }
        - analysis:
            templates:
              - templateName: rollout-analysis
            args:
              - name: service-name
                value: frontend-preview

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-stable
spec:
  selector:
    app: frontend
    rollouts-pod-template-hash: placeholder-stable
  ports:
    - port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-preview
spec:
  selector:
    app: frontend
    rollouts-pod-template-hash: placeholder-preview
  ports:
    - port: 80
      targetPort: 80

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: frontend
  annotations:
    argoproj.io/managed-by-rollouts: "true"
spec:
  hosts:
    - frontend.default.svc.cluster.local
  gateways:
    - mesh
  http:
    - route:
        - destination:
            host: frontend-stable
            port:
              number: 80
          weight: 100
        - destination:
            host: frontend-preview
            port:
              number: 80
          weight: 0

---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: rollout-analysis
  namespace: default
spec:
  metrics:
  - name: simple-success-rate
    interval: 10s
    successCondition: result >= 0.8
    failureCondition: result < 0.8
    count: 3
    failureLimit: 1
    inconclusiveLimit: 2
    provider:
      prometheus:
        address: http://172.16.51.60:30669
        query: |
          scalar(
            sum(rate(istio_requests_total{destination_service="frontend-preview.default.svc.cluster.local", response_code=~"2.*"}[1m]))
            /
            sum(rate(istio_requests_total{destination_service="frontend-preview.default.svc.cluster.local"}[1m]))
          )
  - name: avg-request-duration
    interval: 10s
    successCondition: result <= 1000
    failureCondition: result > 1000
    count: 3
    failureLimit: 1
    inconclusiveLimit: 2
    provider:
      prometheus:
        address: http://172.16.51.60:30669
        query: |
          scalar(
            sum(rate(istio_request_duration_milliseconds_sum{destination_service="frontend-preview.default.svc.cluster.local"}[1m]))
            /
            sum(rate(istio_request_duration_milliseconds_count{destination_service="frontend-preview.default.svc.cluster.local"}[1m]))
          )

